# Generated by Django 5.2.16 on 2026-08-21 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fasttrack', '0004_workflow_collaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('FICHE_PAIE', 'Fiche de paie'), ('ATTESTATION_TRAVAIL', 'Attestation de travail'), ('RELEVE_BANQUE', 'Relevé bancaire')], max_length=32)),
                ('file', models.FileField(upload_to='client_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('CONFORME', 'Conforme'), ('EXPIRE', 'Expiré'), ('MANQUANT', 'Manquant')], default='MANQUANT', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ged_documents', to='fasttrack.clientprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('client', 'document_type'), name='unique_client_document_type')],
            },
        ),
    ]
