# Generated by Django 5.2.16 on 2026-08-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('CIN', 'CIN'), ('FICHE_PAIE', 'Fiche de paie'), ('ATTESTATION_TRAVAIL', 'Attestation de travail'), ('RELEVE_BANQUE', 'Relevé bancaire'), ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile')], max_length=32),
        ),
    ]
