# Generated by Django 5.2.16 on 2026-08-25 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_clientdocument_document_type'),
        ('fasttrack', '0007_alter_clientprofile_telephone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='extracted_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='ocr_status',
            field=models.CharField(default='NOT_APPLICABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ClientContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='contract_signatures/%Y/%m/')),
                ('contract_pdf', models.FileField(upload_to='client_contracts/%Y/%m/')),
                ('signed_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signature', to='fasttrack.clientprofile')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_client_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signature de contrat',
                'verbose_name_plural': 'signatures de contrats',
            },
        ),
    ]
