# Generated by Django 5.2.16 on 2026-08-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasttrack', '0006_client_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
